FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Копируем файл проекта из подпапки
COPY VercelTest/VercelTest.csproj ./
RUN dotnet restore

# Копируем исходный код из подпапки
COPY VercelTest/Program.cs ./
RUN dotnet publish -c Release --no-restore -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish ./


ENV PORT=80 DOTNET_EnableDiagnostics=0
ENTRYPOINT ["dotnet", "VercelTest.dll"]
