FROM ://microsoft.com AS build
WORKDIR /src

# Копируем файл проекта из подпапки
COPY VercelTest/VercelTest.csproj ./
RUN dotnet restore

# Копируем исходный код из подпапки
COPY VercelTest/Program.cs ./
RUN dotnet publish -c Release --no-restore -o /app/publish /p:UseAppHost=false

FROM ://microsoft.com
WORKDIR /app
COPY --from=build /app/publish ./

# Оставляем безопасный порт 8080 для chiseled-образа
ENV PORT=8080 DOTNET_EnableDiagnostics=0
ENTRYPOINT ["dotnet", "VercelTest.dll"]
